# Example of using our ExplainAnomaliesUsingSHAP code on data taken from kaggle: https://www.kaggle.com/mlg-ulb/creditcardfraud

In [ ]:
from ExplainAnomaliesUsingSHAP import ExplainAnomaliesUsingSHAP
import pandas as pd

# Normaliztion of data

In [2]:
df = pd.read_csv('../data/creditcard.csv', delimiter=',')
df = df.drop(['Time'], axis=1)
for col in df.columns[:-1]:
    min_val = df[col].min()
    max_val = df[col].max()
    if min_val != max_val:
        df[col] = (df[col] - min_val) / (max_val - min_val)
        
df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.935192,0.766490,0.881365,0.313023,0.763439,0.267669,0.266815,0.786444,0.475312,0.510600,...,0.561184,0.522992,0.663793,0.391253,0.585122,0.394557,0.418976,0.312697,0.005824,0
1,0.978542,0.770067,0.840298,0.271796,0.766120,0.262192,0.264875,0.786298,0.453981,0.505267,...,0.557840,0.480237,0.666938,0.336440,0.587290,0.446013,0.416345,0.313423,0.000105,0
2,0.935217,0.753118,0.868141,0.268766,0.762329,0.281122,0.270177,0.788042,0.410603,0.513018,...,0.565477,0.546030,0.678939,0.289354,0.559515,0.402727,0.415489,0.311911,0.014739,0
3,0.941878,0.765304,0.868484,0.213661,0.765647,0.275559,0.266803,0.789434,0.414999,0.507585,...,0.559734,0.510277,0.662607,0.223826,0.614245,0.389197,0.417669,0.314371,0.004807,0
4,0.938617,0.776520,0.864251,0.269796,0.762975,0.263984,0.268968,0.782484,0.490950,0.524303,...,0.561327,0.547271,0.663392,0.401270,0.566343,0.507497,0.420561,0.317490,0.002724,0

# Split to Train and Test

In [3]:
X = df.iloc[:,:-1]
y = df.iloc[:, -1]

print('x shape:', X.shape)
print('y shape:', y.shape)
print(y.value_counts())

train_idx = y[y==0].index.values
test_idx = y[y==1].index.values

X_train = X.iloc[train_idx]
y_train = y[train_idx]

X_test = X.iloc[test_idx]
y_test = y[test_idx]

x shape: (284807, 29)
y shape: (284807,)
0    284315
1       492
Name: Class, dtype: int64

# Get explnation

In [4]:
exp_model = ExplainAnomaliesUsingSHAP(num_anomalies_to_explain=10)

In [5]:
all_sets_explaining_features = exp_model.explain_unsupervised_data(x_train=X_train, 
                                                                   x_explain=X_test,
                                                                   return_shap_values=True)

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 29)]              0
_________________________________________________________________
dense (Dense)                (None, 14)                420
_________________________________________________________________
dense_1 (Dense)              (None, 7)                 105
_________________________________________________________________
dense_2 (Dense)              (None, 14)                112
_________________________________________________________________
dense_3 (Dense)              (None, 29)                435
=================================================================
Total params: 1,072
Trainable params: 1,072
Non-trainable params: 0
_________________________________________________________________
WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>
Train on 255883 samples, validate on 28432 samples
Epoch 1/10
255883/255883 - 8s - loss: 0.0024 - mse: 0.0023 - val_loss: 0.0012 - val_mse: 0.0012
Epoch 2/10
255883/255883 - 8s - loss: 0.0012 - mse: 0.0012 - val_loss: 9.7971e-04 - val_mse: 9.4585e-04
Epoch 3/10
255883/255883 - 8s - loss: 9.4128e-04 - mse: 9.0603e-04 - val_loss: 7.7618e-04 - val_mse: 7.3871e-04
Epoch 4/10
255883/255883 - 8s - loss: 7.9653e-04 - mse: 7.6116e-04 - val_loss: 7.5711e-04 - val_mse: 7.2357e-04
Epoch 5/10
255883/255883 - 8s - loss: 7.7851e-04 - mse: 7.4647e-04 - val_loss: 7.5049e-04 - val_mse: 7.1972e-04
Epoch 6/10
255883/255883 - 8s - loss: 7.7088e-04 - mse: 7.4122e-04 - val_loss: 7.4166e-04 - val_mse: 7.1278e-04
Epoch 7/10
255883/255883 - 9s - loss: 7.6278e-04 - mse: 7.3418e-04 - val_loss: 7.3703e-04 - val_mse: 7.0830e-04
Epoch 8/10
255883/255883 - 9s - loss: 7.5110e-04 - mse: 7.2236e-04 - val_loss: 7.3026e-04 - val_mse: 7.0129e-04
Epoch 9/10
255883/255883 - 9s - loss: 7.4219e-04 - mse: 7.1342e-04 - val_loss: 7.2397e-04 - val_mse: 6.9522e-04
Epoch 10/10
255883/255883 - 8s - loss: 7.3582e-04 - mse: 7.0741e-04 - val_loss: 7.2062e-04 - val_mse: 6.9238e-04
WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>
154587
154684
154371
154234
150644
150647
150665
150654
42528
42635

In [6]:
all_sets_explaining_features

{154587: [('V4', -1),
  ('V11', 0.0731265756822315),
  ('V15', 0.02369090910031154),
  ('V7', 0.016886018593518293),
  ('V3', 0.016570416382713796),
  ('V13', 0.015665877182100774),
  ('V10', 0.014052846919758964),
  ('V18', 0.00019320900654557518),
  ('V1', 0.00017568476566009978),
  ('V17', 0.00017336466464923974),
  ('V9', 0.0006888261077363056),
  ('V21', 0.0020651601972084717),
  ('V12', 0.0018995651805052225),
  ('V6', 0.001422672056074865),
  ('V8', -1)],
 154684: [('V4', -1),
  ('V11', 0.06857125766422263),
  ('V15', 0.024017587211378415),
  ('V13', 0.01748191127094885),
  ('V7', 0.01707902271076717),
  ('V3', 0.01379392178383141),
  ('V10', 0.01240802991961949),
  ('V1', -1),
  ('V18', 0.0025376704074176696),
  ('V9', 0.000837353113461579),
  ('V17', 0.00358466848771998),
  ('V12', 0.002072845369657088),
  ('V21', 0.0020574753036938336),
  ('V22', 0.00046080208520149593),
  ('V8', -1),
  ('V24', 0.0003597983812910178)],
 154371: [('V4', -1),
  ('V11', 0.08294142890489672),
  ('V15', 0.02898130105862798),
  ('V3', 0.01590907677201072),
  ('V7', 0.014711642443088473),
  ('V13', 0.014587836279879807),
  ('V10', 0.013403577555324252),
  ('V18', 0.0003123828531369758),
  ('V1', 0.0001992197589061244),
  ('V17', 0.00017078683719280304),
  ('V12', 0.002066954758604087),
  ('V24', 0.0016792627630605912),
  ('V21', 0.0016285431507732772)],
 154234: [('V18', -1),
  ('V15', 0.04582284749101369),
  ('V4', 0.01298634659155869),
  ('V24', 0.005400751656493175),
  ('V11', 0.004962711118773501),
  ('V1', 0.004888440731168236),
  ('V9', 0.004203121378734948),
  ('V17', -1),
  ('V7', 0.0028306002556112014),
  ('V3', 0.0026911820955583705),
  ('V10', 0.0019216298091299933),
  ('V12', 0.0011375011534669778),
  ('V13', 0.01092450612555844),
  ('V16', 9.700471898336474e-05)],
 150644: [('V12', -1),
  ('V11', 0.010486840442011657),
  ('V17', 0.004155066659667708),
  ('V4', 0.003106695971850944),
  ('V13', 0.0028908881702827925),
  ('V24', 0.001753354192488222),
  ('V14', 0.001660075517201605),
  ('V15', 0.004020149749684945),
  ('V18', 0.0034792307493295323),
  ('V10', 0.0012823640295097126),
  ('V16', 0.007824932111410356)],
 150647: [('V12', -1),
  ('V11', 0.009069677191330994),
  ('V4', 0.00438623604807333),
  ('V17', 0.0036944688557951216),
  ('V26', 0.0025862953143419055),
  ('V24', 0.002056737456413358),
  ('V14', 0.0014729120689511745),
  ('V18', 0.0035930031667444967),
  ('V15', 0.001178029124017615),
  ('V16', 0.001203094323917563),
  ('V19', 0.0007287963722595273)],
 150665: [('V17', -1),
  ('V24', 0.006989545665981571),
  ('V11', 0.006511480206894255),
  ('V4', 0.003946292279777723),
  ('V15', 0.003525485111059065),
  ('V18', 0.003038005743877573),
  ('V12', 0.002472561714746555),
  ('V16', 0.008939958118581916),
  ('V19', 0.007667361038725944)],
 150654: [('V12', -1),
  ('V11', 0.009297464939338189),
  ('V4', 0.003955479118907272),
  ('V17', 0.003865460078225134),
  ('V24', 0.0019398804405763668),
  ('V26', 0.0018423242061232359),
  ('V14', 0.0016718447008473962),
  ('V18', 0.0033557790402469314),
  ('V3', 0.0012585499497945432),
  ('V7', 0.0011889138875021267),
  ('V16', 0.0010422633904812783)],
 42528: [('V17', -1),
  ('V24', 0.006736426024435591),
  ('V18', 0.0050778753111189595),
  ('V12', 0.002842628989519194),
  ('V4', 0.0024794057912630846),
  ('V14', 0.002269837239830145),
  ('V11', 0.002218586625682887),
  ('V19', 0.0016399651294882627),
  ('V16', 0.0013763903992034172),
  ('V9', 0.004386193418645018),
  ('V26', 0.001635154304709785),
  ('V10', 0.0010430554925531486),
  ('V13', 0.0009982975334452363)],
 42635: [('V17', -1),
  ('V24', 0.00605546732778159),
  ('V18', 0.004766048030447719),
  ('V4', 0.002795297282351012),
  ('V11', 0.0021679928865168505),
  ('V12', 0.0020859762105622697),
  ('V15', 0.0019091023771055922),
  ('V14', 0.0014634281110916776),
  ('V10', 0.001426458113448244),
  ('V19', 0.012697520780446276),
  ('V16', 0.01025355503344674),
  ('V13', 0.0018196956159556073)]}